name: Count Downloads

on:
  release:
    types: [published]

jobs:
  update-download-count:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Increment download count
        run: |
          COUNT_FILE="download_count.json"

          # Verifica si el archivo de conteo existe, si no, créalo con un conteo inicial de 0
          if [ ! -f $COUNT_FILE ]; then
            echo '{"downloads": 0}' > $COUNT_FILE
          fi

          # Leer el conteo actual y actualizarlo
          CURRENT_COUNT=$(jq '.downloads' $COUNT_FILE)
          UPDATED_COUNT=$((CURRENT_COUNT + 1))
          jq --argjson new_count $UPDATED_COUNT '.downloads = $new_count' $COUNT_FILE > $COUNT_FILE.tmp
          mv $COUNT_FILE.tmp $COUNT_FILE

          # Configurar el usuario y la rama para hacer commit
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          
          # Crear una nueva rama para los cambios
          git checkout -b update-download-count
          
          git add $COUNT_FILE
          git commit -m "Increment download count"
          
          # Hacer push a la nueva rama
          git push origin update-download-count
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
